### ISSUE TITLE
Getting "No matching state found in storage" error 

### ISSUE THREAD

**Issue by YogiDhingani27** [authts/react-oidc-context#1223] opened 2024-04-30 12:25 UTC
When I'm trying to visit a url which has a code as a query param then authentication is failing and giving this error.

Other urls are working fine for ex: http://localhost:3004/integration

Not working url: 

http://localhost:3000/integration?state=%7B%22uuid%22:%20%1234%22,%20%22platform%22:%20%22google%22%7D&code=1233434&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/drive.readonly%20openid&authuser=0&hd=werwer.com&prompt=consent

![image](https://github.com/authts/react-oidc-context/assets/94128664/472a749a-a625-4be2-8423-57500ff95c0d)

Note: Excluding url having code as a query parameter other urls are working fine.

I want a code query parameter in my url for OAuth related authentication.

**Comment by YogiDhingani27** [comment] 2024-05-01 03:48
UserManager Configuration:

`export const userManager = new UserManager({
    authority: authority,
    client_id: clientId,
    redirect_uri: window.location.origin + window.location.pathname,
    post_logout_redirect_uri: window.location.origin,
    monitorSession: true
});`

I'm using keycloak for authentication.

**Comment by zach-betz-hln** [comment] 2024-05-02 19:54
Possible duplicate of https://github.com/authts/oidc-client-ts/issues/1487

**Closed** 2024-10-04 15:18 UTC
Labels: duplicate
