### ISSUE TITLE
Attempted import error: 'UserManager' is not exported from 'oidc-client-ts'.

### ISSUE THREAD

**Issue by pamapa** [authts/react-oidc-context#133] opened 2021-11-05 14:27 UTC
When using the react-oidc-context library v2.0.0.beta.1 in a project:

./node_modules/react-oidc-context/dist/react-oidc-context.mjs
Attempted import error: 'UserManager' is not exported from 'oidc-client-ts'.

**Comment by pamapa** [comment] 2021-11-05 14:32
UserManager is exported:
```
// package.json
var version = "2.0.0-beta.3";

// src/Version.ts
var Version = version;
export {
  AccessTokenEvents,
  CheckSessionIFrame,
  InMemoryWebStorage,
  Log,
  MetadataService,
  OidcClient,
  SessionMonitor,
  TokenRevocationClient,
  User,
  UserManager,
  UserManagerEvents,
  Version,
  WebStorageStateStore
};
```

**Comment by pamapa** [comment] 2021-11-05 14:54
when using "moduleResolution": "node"

oidc-client-ts.cjs

**Comment by qlerolland** [comment] 2021-11-05 15:17
> When using the react-oidc-context library in a project:
> 
> ./node_modules/react-oidc-context/dist/react-oidc-context.mjs Attempted import error: 'UserManager' is not exported from 'oidc-client-ts'.

Have you installed _oidc-client-ts_ ? (Which is a peerDependency)

**Comment by pamapa** [comment] 2021-11-05 15:39
Yes.

I am confused why it takes react-oidc-context.mjs, which is an esm module, where my project is using node resolution, should it not take react-oidc-context.cjs? ...

**Comment by pamapa** [comment] 2021-11-05 16:13
strange wise webpack (create react app) is mixing module(esm) and main(commonjs), why?
- react-oidc-context (esm)
- oidc-client-ts (commonjs)

**Comment by pamapa** [comment] 2021-11-09 09:57
The problem seems to be the the `.mjs` extension.
When i rename react-oidc-context.mjs to react-oidc-context.esm.js and adapt package.json accordingly it magically works.

https://webpack.js.org/guides/ecma-script-modules/

@kherock 
I will change the esm name in this package + oidc-client-ts unless you have a better idea? This way webpack will autotetect the correct format...

**Comment by kherock** [comment] 2021-11-09 13:39
I can't reproduce this, and the .mjs extension is important for native ESM support from Node. I was actually going to suggest moving to the package `exports` field ahead of the 2.0 release.

What version of Node are you running, and what does your webpack config look like?

**Comment by pamapa** [comment] 2021-11-09 13:57
We

**Comment by pamapa** [comment] 2021-11-09 14:00
We can change this back + make a fix. I was unable to find another solution yet.

We are using react create app (https://www.npmjs.com/package/react-scripts v4.0.3), which is using under the hood webpack v4. 

Docu:
https://create-react-app.dev/docs/getting-started/

**Comment by kherock** [comment] 2021-11-09 14:16
Ok, Webpack v4 is really the problem here. I think migrating to `exports` should solve this. Webpack 4 doesn't implement resolution for those and will just use the CJS bundle. Can you let me know if a package.json like the following fixes it?

```json
  "main": "dist/oidc-client-ts.cjs",
  "types": "dist/oidc-client-ts.d.ts"
  "exports": {
    ".": {
      "import": "./dist/oidc-client-ts.mjs",
      "require": "./dist/oidc-client-ts.cjs"
    },
    "./package.json": "./package.json"
  }
  // ...
```

**Comment by kherock** [comment] 2021-11-09 14:21
I think this is relevant:
https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022

**Comment by pamapa** [comment] 2021-11-09 15:10
> ```json
> "exports": {
>     ".": {
>       "import": "./dist/react-oidc-context.mjs",
>       "require": "./dist/react-oidc-context.cjs"
>     },
>     "./package.json": "./package.json"
>   }
> ```

still leads to this error:
```
./node_modules/react-oidc-context/dist/react-oidc-context.mjs
Attempted import error: 'UserManager' is not exported from 'oidc-client-ts'.
```

**Comment by pamapa** [comment] 2021-11-09 15:20
```json
  "main": "dist/react-oidc-context.cjs",
  "types": "dist/react-oidc-context.d.ts",
  "exports": {
    ".": {
      "import": "./dist/react-oidc-context.mjs",
      "require": "./dist/react-oidc-context.cjs"
    },
    "./package.json": "./package.json"
  }
```

leads to:
```
./src/index.tsx
Attempted import error: 'AuthProvider' is not exported from 'react-oidc-context'.
```

**Comment by pamapa** [comment] 2021-11-10 07:14
I am wondering if it would make sense to wait for react-scripts v5, where they have switched to webpack v5. Within their milestone there is only one issue left. On the other hand we could go now with webapck v4 support and later drop that by using mjs extenstion...

**Closed** 2021-11-10 07:45 UTC
Labels: bug
